services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    env_file: 
      .env
    restart: always
    environment:
      - ISC_CPF_MERGE_FILE=/home/irisowner/dev/merge.cpf
    ports:
      - 9092:52773  # Management Portal / REST APIs - http://localhost:9092/csp/sys/UtilHome.csp
      - 9091:1972   # SuperServer port
      - 9093:8080
    volumes:
      - ./:/home/irisowner/dev
